In [1]:
import numpy as np
import pandas as pd
import scanpy as sc

In [2]:
adata = sc.read_h5ad('/data1/normantm/datasets/Hs27_CRISPRa/fibroblast_CRISPRa_mean_pop.h5ad')

In [22]:
adata.var

,feature_types,genome,mean,in_matrix,std,cv,fano,pairwise_p_cost,mean_adjusted_pairwise_p_cost,excess_cv,pairwise_chosen,gene_id
gene_name,,,,,,,,,,,,
DPM1,Gene Expression,GRCh38,0.496894,True,0.763064,1.535669,1.171814,NaN,NaN,0.996323,False,ENSG00000000419
FUCA2,Gene Expression,GRCh38,0.825598,True,1.019301,1.234621,1.258451,-2.688921,0.028040,0.993769,False,ENSG00000001036
NIPAL3,Gene Expression,GRCh38,0.356259,True,0.642933,1.804680,1.160289,NaN,NaN,1.019038,False,ENSG00000001461
ANKIB1,Gene Expression,GRCh38,0.473726,True,0.739542,1.561119,1.154513,NaN,NaN,1.000408,False,ENSG00000001629
CYP51A1,Gene Expression,GRCh38,0.781959,True,1.036694,1.325765,1.374412,-2.689456,0.038956,1.047946,False,ENSG00000001630
...,...,...,...,...,...,...,...,...,...,...,...,...
EBLN3P,Gene Expression,GRCh38,0.287453,True,0.561701,1.954063,1.097600,NaN,NaN,1.000352,False,ENSG00000281649
AC092807.3,Gene Expression,GRCh38,0.343467,True,0.640401,1.864520,1.194040,NaN,NaN,1.030825,False,ENSG00000282057
AC010642.2,Gene Expression,GRCh38,0.446480,True,0.707841,1.585381,1.122197,NaN,NaN,0.986700,False,ENSG00000283103
SCO2,Gene Expression,GRCh38,0.281562,True,0.551599,1.959067,1.080620,NaN,NaN,0.991122,False,ENSG00000284194
POLR2J3,Gene Expression,GRCh38,0.725420,True,0.995076,1.371724,1.364970,-2.787869,-0.043632,1.051133,False,ENSG00000285437

In [23]:
adata.

,protospacer,target_gene,target_expr,active,cluster,cluster_name,cluster_description,gene_driven,sequence_driven,sequence_suffix,...,best_guide_rpe1,seed_driven_fibro,seed_driven_rpe1,active_fibro,expanded_active_fibro,de_genes_fibro,active_rpe1,expanded_active_rpe1,de_genes_rpe1,final_tf_library
guide_identity,,,,,,,,,,,,,,,,,,,,,
AATF_GCGCAGAAGGTTGAAGGGAT,GCGCAGAAGGTTGAAGGGAT,AATF,NaN,False,40.0,NaN,40: neither (28),False,False,,...,False,False,True,False,False,12.0,False,False,28.0,False
AATF_GCGTGCGAGTGCGCGGGAAG,GCGTGCGAGTGCGCGGGAAG,AATF,NaN,False,2144.0,NaN,2144: SEQUENCE-driven (GGGAAG) (2),False,True,GGGAAG,...,False,False,False,False,False,10.0,False,False,98.0,False
AATF_GGAAGCGCGCAGAAGGTTGA,GGAAGCGCGCAGAAGGTTGA,AATF,NaN,False,776.0,NaN,776: neither (5),False,False,,...,True,False,False,False,False,0.0,False,False,4.0,True
AATF_GGAAGGGATTGGAGCCGTAT,GGAAGGGATTGGAGCCGTAT,AATF,NaN,False,949.0,NaN,949: neither (3),False,False,,...,False,False,False,False,False,1.0,False,False,1.0,True
AATF_GGGCGTTGCTAGCATGAAGG,GGGCGTTGCTAGCATGAAGG,AATF,NaN,False,1615.0,NaN,1615: SEQUENCE-driven (GAAGG) (17),False,True,GAAGG,...,False,True,False,False,False,11.0,False,False,15.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
off-target_GTCCATAGGGTCTAGCGCCG,GTCCATAGGGTCTAGCGCCG,off-target,NaN,False,298.0,NaN,298: neither (16),False,False,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
off-target_GTCGTTATCTCGCTATTTCG,GTCGTTATCTCGCTATTTCG,off-target,NaN,False,1790.0,NaN,1790: neither (7),False,False,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
off-target_GTGGATTATCTGACGCGAAT,GTGGATTATCTGACGCGAAT,off-target,NaN,False,1613.0,NaN,1613: neither (15),False,False,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
off-target_GTGGTTATACCCGACTAGAC,GTGGTTATACCCGACTAGAC,off-target,NaN,False,1640.0,NaN,1640: neither (10),False,False,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
off-target_GTTCCTGTTGGGTCGCGAAT,GTTCCTGTTGGGTCGCGAAT,off-target,NaN,False,1597.0,NaN,1597: neither (4),False,False,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
adata

AnnData object with n_obs × n_vars = 10916 × 4914
    obs: 'protospacer', 'target_gene', 'target_expr', 'active', 'cluster', 'cluster_name', 'cluster_description', 'gene_driven', 'sequence_driven', 'sequence_suffix', 'bulk_expr', 'expressed', 'p_expressed', 'de_genes', 'strength', 'cell_count', 'target_gene_id', 'masked_active', 'masked_cluster', 'masked_cluster_name', 'masked_cluster_description', 'masked_cluster_size', 'masked_cluster_num_genes', 'stricter_masked_cluster', 'stricter_masked_cluster_description', 'guide_label', 'gene_id', 'ctrl_pctl_fibro', 'target_pctl_fibro', 'pctl_change_fibro', 'adj_p_fibro', 'ctrl_coef_fibro', 'ctrl_abs_fibro', 'target_coef_fibro', 'target_abs_fibro', 'count_profile_fibro', 'ctrl_expressed_fibro', 'is_activated_fibro', 'guide_rank_fibro', 'top_guide_fibro', 'activation_expression_fibro', 'cluster_description_fibro', 'masked_cluster_description_fibro', 'bulk_expr_fibro', 'expressed_fibro', 'p_expressed_fibro', 'cell_count_fibro', 'ctrl_pctl_rpe1', 'target_pctl_rpe1', 'pctl_change_rpe1', 'adj_p_rpe1', 'ctrl_coef_rpe1', 'ctrl_abs_rpe1', 'target_coef_rpe1', 'target_abs_rpe1', 'count_profile_rpe1', 'ctrl_expressed_rpe1', 'is_activated_rpe1', 'guide_rank_rpe1', 'top_guide_rpe1', 'activation_expression_rpe1', 'cluster_description_rpe1', 'masked_cluster_description_rpe1', 'bulk_expr_rpe1', 'expressed_rpe1', 'p_expressed_rpe1', 'cell_count_rpe1', 'bad_seed', 'seed_matches', 'good_guide_fibro', 'good_guide_rpe1', 'best_guide_fibro', 'best_guide_rpe1', 'seed_driven_fibro', 'seed_driven_rpe1', 'active_fibro', 'expanded_active_fibro', 'de_genes_fibro', 'active_rpe1', 'expanded_active_rpe1', 'de_genes_rpe1', 'final_tf_library'
    var: 'feature_types', 'genome', 'mean', 'in_matrix', 'std', 'cv', 'fano', 'pairwise_p_cost', 'mean_adjusted_pairwise_p_cost', 'excess_cv', 'pairwise_chosen', 'gene_id'
    layers: 'adj_p', 'masked', 'p'

In [4]:
#merge with guide metadata
guide_act = pd.read_excel('Supplementary_Table1.xlsx', sheet_name='Table S4 Guide Activity')

In [5]:
guide_act.columns

Index(['guide_identity', 'guide_label', 'protospacer', 'gene_id',
       'target_gene', 'ctrl_pctl_fibro', 'target_pctl_fibro',
       'pctl_change_fibro', 'adj_p_fibro', 'ctrl_coef_fibro', 'ctrl_abs_fibro',
       'target_coef_fibro', 'target_abs_fibro', 'count_profile_fibro',
       'ctrl_expressed_fibro', 'is_activated_fibro', 'guide_rank_fibro',
       'top_guide_fibro', 'activation_expression_fibro',
       'cluster_description_fibro', 'masked_cluster_description_fibro',
       'bulk_expr_fibro', 'expressed_fibro', 'p_expressed_fibro',
       'cell_count_fibro', 'ctrl_pctl_rpe1', 'target_pctl_rpe1',
       'pctl_change_rpe1', 'adj_p_rpe1', 'ctrl_coef_rpe1', 'ctrl_abs_rpe1',
       'target_coef_rpe1', 'target_abs_rpe1', 'count_profile_rpe1',
       'ctrl_expressed_rpe1', 'is_activated_rpe1', 'guide_rank_rpe1',
       'top_guide_rpe1', 'activation_expression_rpe1',
       'cluster_description_rpe1', 'masked_cluster_description_rpe1',
       'bulk_expr_rpe1', 'expressed_rpe1', 'p_expressed_rpe1',
       'cell_count_rpe1', 'bad_seed', 'seed_matches', 'good_guide_fibro',
       'good_guide_rpe1', 'best_guide_fibro', 'best_guide_rpe1',
       'seed_driven_fibro', 'seed_driven_rpe1', 'active_fibro',
       'expanded_active_fibro', 'de_genes_fibro', 'active_rpe1',
       'expanded_active_rpe1', 'de_genes_rpe1', 'final_tf_library'],
      dtype='object')

In [6]:
keep = ['guide_identity','guide_label', 'gene_id',
       'ctrl_pctl_fibro', 'target_pctl_fibro',
       'pctl_change_fibro', 'adj_p_fibro', 'ctrl_coef_fibro', 'ctrl_abs_fibro',
       'target_coef_fibro', 'target_abs_fibro', 'count_profile_fibro',
       'ctrl_expressed_fibro', 'is_activated_fibro', 'guide_rank_fibro',
       'top_guide_fibro', 'activation_expression_fibro',
       'cluster_description_fibro', 'masked_cluster_description_fibro',
       'bulk_expr_fibro', 'expressed_fibro', 'p_expressed_fibro',
       'cell_count_fibro', 'ctrl_pctl_rpe1', 'target_pctl_rpe1',
       'pctl_change_rpe1', 'adj_p_rpe1', 'ctrl_coef_rpe1', 'ctrl_abs_rpe1',
       'target_coef_rpe1', 'target_abs_rpe1', 'count_profile_rpe1',
       'ctrl_expressed_rpe1', 'is_activated_rpe1', 'guide_rank_rpe1',
       'top_guide_rpe1', 'activation_expression_rpe1',
       'cluster_description_rpe1', 'masked_cluster_description_rpe1',
       'bulk_expr_rpe1', 'expressed_rpe1', 'p_expressed_rpe1',
       'cell_count_rpe1', 'bad_seed', 'seed_matches', 'good_guide_fibro',
       'good_guide_rpe1', 'best_guide_fibro', 'best_guide_rpe1',
       'seed_driven_fibro', 'seed_driven_rpe1', 'active_fibro',
       'expanded_active_fibro', 'de_genes_fibro', 'active_rpe1',
       'expanded_active_rpe1', 'de_genes_rpe1', 'final_tf_library']

adata.obs = adata.obs.merge(guide_act[keep], left_index = True, right_on = 'guide_identity', how = 'left').set_index('guide_identity')

In [7]:
hits_fibro = adata.obs[(adata.obs.seed_driven_fibro == False)&(adata.obs.bad_seed == False)&((adata.obs.is_activated_fibro >0)|(adata.obs.active_fibro)|(adata.obs.expanded_active_fibro))]

In [8]:
hits_fibro.is_activated_fibro.sum()

2794.0

In [9]:
hits_fibro

,protospacer,target_gene,target_expr,active,cluster,cluster_name,cluster_description,gene_driven,sequence_driven,sequence_suffix,...,best_guide_rpe1,seed_driven_fibro,seed_driven_rpe1,active_fibro,expanded_active_fibro,de_genes_fibro,active_rpe1,expanded_active_rpe1,de_genes_rpe1,final_tf_library
guide_identity,,,,,,,,,,,,,,,,,,,,,
AATF_GCGCAGAAGGTTGAAGGGAT,GCGCAGAAGGTTGAAGGGAT,AATF,NaN,False,40.0,NaN,40: neither (28),False,False,,...,False,False,True,False,False,12.0,False,False,28.0,False
AATF_GGAAGCGCGCAGAAGGTTGA,GGAAGCGCGCAGAAGGTTGA,AATF,NaN,False,776.0,NaN,776: neither (5),False,False,,...,True,False,False,False,False,0.0,False,False,4.0,True
AATF_GGAAGGGATTGGAGCCGTAT,GGAAGGGATTGGAGCCGTAT,AATF,NaN,False,949.0,NaN,949: neither (3),False,False,,...,False,False,False,False,False,1.0,False,False,1.0,True
AATF_GTGAAGGGATTGGAGCCGTA,GTGAAGGGATTGGAGCCGTA,AATF,NaN,False,1074.0,NaN,1074: neither (8),False,False,,...,False,False,False,False,False,0.0,False,False,7.0,True
ABL1_GCTCGGCCTCGGGAACGCCA,GCTCGGCCTCGGGAACGCCA,ABL1,NaN,False,40.0,NaN,40: neither (28),False,False,,...,True,False,True,False,False,2.0,False,False,26.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZSCAN30_GACAGCTCGCGGCGGTTCGG,GACAGCTCGCGGCGGTTCGG,ZSCAN30,NaN,False,1598.0,NaN,1598: neither (10),False,False,,...,False,False,True,False,False,5.0,False,False,8.0,False
ZSCAN30_GCGGTGACCAAGTCGAGGTA,GCGGTGACCAAGTCGAGGTA,ZSCAN30,NaN,False,1050.0,NaN,1050: neither (7),False,False,,...,False,False,False,False,False,1.0,False,False,4.0,True
ZSCAN5A_GGAAGCAGGAGTGAAGGAGC,GGAAGCAGGAGTGAAGGAGC,ZSCAN5A,NaN,False,1814.0,NaN,1814: neither (7),False,False,,...,False,False,False,False,False,6.0,False,False,8.0,True
ZXDA_GTGGTACTGGGTCTCTGGAA,GTGGTACTGGGTCTCTGGAA,ZXDA,NaN,False,194.0,NaN,194: neither (15),False,False,,...,False,False,False,False,True,6.0,False,False,8.0,True
ZXDB_GAACAGAATAGAAAGCCCAG,GAACAGAATAGAAAGCCCAG,ZXDB,NaN,False,2298.0,NaN,2298: neither (2),False,False,,...,True,False,True,False,False,14.0,False,False,9.0,False

In [10]:
hits_fibro.active_fibro.sum()

520

In [11]:
hits_fibro.expanded_active_fibro.sum()

106

In [12]:
adata.var['mean'].describe()

count    4914.000000
mean        1.518045
std         5.346437
min         0.200040
25%         0.304042
50%         0.497905
75%         1.027166
max       243.130707
Name: mean, dtype: float64

In [13]:
hits_fibro.index

Index(['AATF_GCGCAGAAGGTTGAAGGGAT', 'AATF_GGAAGCGCGCAGAAGGTTGA',
       'AATF_GGAAGGGATTGGAGCCGTAT', 'AATF_GTGAAGGGATTGGAGCCGTA',
       'ABL1_GCTCGGCCTCGGGAACGCCA', 'ACTL6A_GCAGCAGGACAGAAGGAGTT',
       'ACTL6A_GCCCGGGTGGGCGAGGGAAT', 'ACTL6A_GGGGACTAGGAGGTGCGTCT',
       'ADAR_GAAGGCCTGAGAAGATACGT', 'ADAR_GCTCCGCTGCATGAGAACTA',
       ...
       'ZSCAN22_GCGCCACCTCAGTCCCACAA', 'ZSCAN26_GCGCAGAAGGAGACTAACAT',
       'ZSCAN26_GGCCGCTTAGGCATCGCAGA', 'ZSCAN26_GTCGCAGAAGGAGACTAACA',
       'ZSCAN2_GGACCGCGGTCCCCGGAGTA', 'ZSCAN30_GACAGCTCGCGGCGGTTCGG',
       'ZSCAN30_GCGGTGACCAAGTCGAGGTA', 'ZSCAN5A_GGAAGCAGGAGTGAAGGAGC',
       'ZXDA_GTGGTACTGGGTCTCTGGAA', 'ZXDB_GAACAGAATAGAAAGCCCAG'],
      dtype='object', name='guide_identity', length=2868)

In [14]:
hits_expr = adata.to_df().loc[hits_fibro.index]

In [15]:
hits_expr

gene_name,DPM1,FUCA2,NIPAL3,ANKIB1,CYP51A1,KRIT1,BAD,LAP3,CD99,LASP1,...,CISD3,DDX52,GGNBP2,MRPL45,PAGR1,EBLN3P,AC092807.3,AC010642.2,SCO2,POLR2J3
guide_identity,,,,,,,,,,,,,,,,,,,,,
AATF_GCGCAGAAGGTTGAAGGGAT,-0.131924,-0.319254,0.001023,-0.009598,0.055696,0.354959,-0.240341,-0.284079,-0.253161,0.150592,...,-0.105325,0.022438,-0.021837,0.114472,0.078340,-0.115472,-0.153524,-0.065819,-0.314338,-0.050019
AATF_GGAAGCGCGCAGAAGGTTGA,-0.117437,-0.261913,-0.585374,-0.082855,0.277983,-0.184340,-0.336881,0.164714,-0.529625,0.710519,...,-0.517014,1.122795,0.882859,0.200050,0.358649,-0.641648,-0.341816,-0.155178,-0.487522,1.110840
AATF_GGAAGGGATTGGAGCCGTAT,0.405888,-0.299869,-0.222511,0.067499,-0.165533,-0.205277,-0.021107,-0.233354,-0.017067,-0.069593,...,-0.010207,0.149588,-0.109745,0.173841,0.148020,-0.153114,-0.141280,0.192178,0.162314,0.120998
AATF_GTGAAGGGATTGGAGCCGTA,-0.270689,0.457040,-0.262338,0.228873,-0.120255,0.117843,-0.026789,0.049870,0.057909,-0.346970,...,0.124197,0.141521,0.151179,-0.124533,-0.428368,-0.132562,0.238572,-0.167052,-0.379478,-0.117762
ABL1_GCTCGGCCTCGGGAACGCCA,-0.285401,-0.013690,-0.136254,0.094237,-0.120662,0.128675,-0.287257,-0.184541,0.363956,0.242474,...,-0.085997,0.262554,0.213346,-0.167361,-0.103087,-0.141717,-0.325445,-0.199632,0.396402,-0.220176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZSCAN30_GACAGCTCGCGGCGGTTCGG,-0.346016,-0.295584,0.266849,0.307925,-0.129927,-0.139675,0.332149,-0.151357,-0.260907,-0.007564,...,-0.504111,0.567197,0.017662,0.054242,-0.016369,-0.079187,-0.297625,-0.030736,-0.075851,0.552078
ZSCAN30_GCGGTGACCAAGTCGAGGTA,-0.020017,-0.241313,-0.113757,-0.024405,0.114818,0.298441,0.142873,0.068739,-0.295667,-0.133191,...,-0.141563,-0.222401,-0.200504,-0.124560,-0.117338,-0.223809,0.029853,-0.151811,0.034667,-0.199736
ZSCAN5A_GGAAGCAGGAGTGAAGGAGC,-0.234326,0.202045,0.190804,-0.084709,-0.017279,0.042115,0.687867,-0.216517,0.376974,-0.174405,...,-0.102208,0.181515,0.013013,-0.037041,-0.366281,-0.222314,-0.192057,0.253446,-0.279497,0.083255
ZXDA_GTGGTACTGGGTCTCTGGAA,0.124193,0.003644,0.154515,-0.181482,0.021999,-0.087250,-0.208173,-0.104753,-0.128535,0.078658,...,0.345679,-0.306511,0.248049,-0.124021,0.321670,0.317132,0.230196,0.076179,0.047921,0.227569
ZXDB_GAACAGAATAGAAAGCCCAG,-0.174906,0.049887,-0.240390,0.144902,-0.026979,-0.309071,-0.514595,-0.049548,0.042436,-0.297499,...,0.057472,-0.247413,-0.235022,-0.055151,0.035410,0.144641,0.117310,0.528235,0.414389,0.388902

In [16]:
adata.var

,feature_types,genome,mean,in_matrix,std,cv,fano,pairwise_p_cost,mean_adjusted_pairwise_p_cost,excess_cv,pairwise_chosen,gene_id
gene_name,,,,,,,,,,,,
DPM1,Gene Expression,GRCh38,0.496894,True,0.763064,1.535669,1.171814,NaN,NaN,0.996323,False,ENSG00000000419
FUCA2,Gene Expression,GRCh38,0.825598,True,1.019301,1.234621,1.258451,-2.688921,0.028040,0.993769,False,ENSG00000001036
NIPAL3,Gene Expression,GRCh38,0.356259,True,0.642933,1.804680,1.160289,NaN,NaN,1.019038,False,ENSG00000001461
ANKIB1,Gene Expression,GRCh38,0.473726,True,0.739542,1.561119,1.154513,NaN,NaN,1.000408,False,ENSG00000001629
CYP51A1,Gene Expression,GRCh38,0.781959,True,1.036694,1.325765,1.374412,-2.689456,0.038956,1.047946,False,ENSG00000001630
...,...,...,...,...,...,...,...,...,...,...,...,...
EBLN3P,Gene Expression,GRCh38,0.287453,True,0.561701,1.954063,1.097600,NaN,NaN,1.000352,False,ENSG00000281649
AC092807.3,Gene Expression,GRCh38,0.343467,True,0.640401,1.864520,1.194040,NaN,NaN,1.030825,False,ENSG00000282057
AC010642.2,Gene Expression,GRCh38,0.446480,True,0.707841,1.585381,1.122197,NaN,NaN,0.986700,False,ENSG00000283103
SCO2,Gene Expression,GRCh38,0.281562,True,0.551599,1.959067,1.080620,NaN,NaN,0.991122,False,ENSG00000284194
POLR2J3,Gene Expression,GRCh38,0.725420,True,0.995076,1.371724,1.364970,-2.787869,-0.043632,1.051133,False,ENSG00000285437

In [17]:
adata.obs

,protospacer,target_gene,target_expr,active,cluster,cluster_name,cluster_description,gene_driven,sequence_driven,sequence_suffix,...,best_guide_rpe1,seed_driven_fibro,seed_driven_rpe1,active_fibro,expanded_active_fibro,de_genes_fibro,active_rpe1,expanded_active_rpe1,de_genes_rpe1,final_tf_library
guide_identity,,,,,,,,,,,,,,,,,,,,,
AATF_GCGCAGAAGGTTGAAGGGAT,GCGCAGAAGGTTGAAGGGAT,AATF,NaN,False,40.0,NaN,40: neither (28),False,False,,...,False,False,True,False,False,12.0,False,False,28.0,False
AATF_GCGTGCGAGTGCGCGGGAAG,GCGTGCGAGTGCGCGGGAAG,AATF,NaN,False,2144.0,NaN,2144: SEQUENCE-driven (GGGAAG) (2),False,True,GGGAAG,...,False,False,False,False,False,10.0,False,False,98.0,False
AATF_GGAAGCGCGCAGAAGGTTGA,GGAAGCGCGCAGAAGGTTGA,AATF,NaN,False,776.0,NaN,776: neither (5),False,False,,...,True,False,False,False,False,0.0,False,False,4.0,True
AATF_GGAAGGGATTGGAGCCGTAT,GGAAGGGATTGGAGCCGTAT,AATF,NaN,False,949.0,NaN,949: neither (3),False,False,,...,False,False,False,False,False,1.0,False,False,1.0,True
AATF_GGGCGTTGCTAGCATGAAGG,GGGCGTTGCTAGCATGAAGG,AATF,NaN,False,1615.0,NaN,1615: SEQUENCE-driven (GAAGG) (17),False,True,GAAGG,...,False,True,False,False,False,11.0,False,False,15.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
off-target_GTCCATAGGGTCTAGCGCCG,GTCCATAGGGTCTAGCGCCG,off-target,NaN,False,298.0,NaN,298: neither (16),False,False,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
off-target_GTCGTTATCTCGCTATTTCG,GTCGTTATCTCGCTATTTCG,off-target,NaN,False,1790.0,NaN,1790: neither (7),False,False,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
off-target_GTGGATTATCTGACGCGAAT,GTGGATTATCTGACGCGAAT,off-target,NaN,False,1613.0,NaN,1613: neither (15),False,False,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
off-target_GTGGTTATACCCGACTAGAC,GTGGTTATACCCGACTAGAC,off-target,NaN,False,1640.0,NaN,1640: neither (10),False,False,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
off-target_GTTCCTGTTGGGTCGCGAAT,GTTCCTGTTGGGTCGCGAAT,off-target,NaN,False,1597.0,NaN,1597: neither (4),False,False,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
adata.to_df(layer = 'adj_p').loc[hits_fibro.index]

gene_name,DPM1,FUCA2,NIPAL3,ANKIB1,CYP51A1,KRIT1,BAD,LAP3,CD99,LASP1,...,CISD3,DDX52,GGNBP2,MRPL45,PAGR1,EBLN3P,AC092807.3,AC010642.2,SCO2,POLR2J3
guide_identity,,,,,,,,,,,,,,,,,,,,,
AATF_GCGCAGAAGGTTGAAGGGAT,0.885145,0.686927,0.997446,0.993146,0.958307,0.644633,0.745341,0.718741,0.734589,0.868880,...,0.917128,0.984674,0.984674,0.907706,0.942166,0.903237,0.868880,0.948454,0.686737,0.962141
AATF_GGAAGCGCGCAGAAGGTTGA,0.999802,0.999802,0.999802,0.999802,0.999802,0.999802,0.999802,0.999802,0.999802,0.999802,...,0.999802,0.999802,0.999802,0.999802,0.999802,0.999802,0.999802,0.999802,0.999802,0.999802
AATF_GGAAGGGATTGGAGCCGTAT,0.414525,0.729601,0.835514,0.972485,0.895787,0.873679,0.998456,0.833198,0.998456,0.969996,...,0.999299,0.895787,0.931975,0.895787,0.895787,0.895787,0.896927,0.884206,0.895787,0.920381
AATF_GTGAAGGGATTGGAGCCGTA,0.944074,0.944074,0.944074,0.944074,0.970366,0.970366,0.983063,0.972503,0.971300,0.944074,...,0.970366,0.963780,0.960945,0.970366,0.944074,0.963780,0.944074,0.958260,0.944074,0.970366
ABL1_GCTCGGCCTCGGGAACGCCA,0.875982,0.994719,0.940723,0.953242,0.948029,0.943622,0.877070,0.918108,0.797019,0.904460,...,0.960815,0.899479,0.907861,0.921144,0.951574,0.936350,0.840298,0.910141,0.787401,0.906147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZSCAN30_GACAGCTCGCGGCGGTTCGG,0.828672,0.889895,0.903510,0.880269,0.968687,0.963437,0.852361,0.956295,0.903510,0.995236,...,0.547799,0.424827,0.994187,0.982762,0.994187,0.971651,0.889895,0.988323,0.972201,0.460455
ZSCAN30_GCGGTGACCAAGTCGAGGTA,0.983811,0.699946,0.889999,0.979092,0.891969,0.659837,0.856931,0.945213,0.664149,0.865042,...,0.857445,0.727897,0.752480,0.879209,0.887859,0.707268,0.977435,0.844726,0.970599,0.754619
ZSCAN5A_GGAAGCAGGAGTGAAGGAGC,0.788702,0.830805,0.840793,0.931617,0.981439,0.963950,0.092697,0.827523,0.655097,0.850815,...,0.920530,0.845881,0.986627,0.963950,0.663517,0.792406,0.840793,0.776237,0.747288,0.933862
ZXDA_GTGGTACTGGGTCTCTGGAA,0.932797,0.999096,0.911626,0.895633,0.992443,0.956482,0.875162,0.948874,0.932797,0.957951,...,0.772755,0.783239,0.835600,0.932797,0.782985,0.779225,0.840350,0.962562,0.976060,0.852475
ZXDB_GAACAGAATAGAAAGCCCAG,0.846739,0.975767,0.771051,0.872782,0.989282,0.670012,0.448865,0.977059,0.980867,0.689683,...,0.967385,0.764693,0.774013,0.968590,0.985098,0.872782,0.909450,0.432144,0.551443,0.596825

In [19]:
sig_genes = (adata.to_df(layer = 'adj_p').loc[hits_fibro.index] < 0.05).sum()

In [20]:
hits_expr.to_csv('hit_guides_by_genes.tsv', sep = '\t')

In [122]:
#promoter coordinates, differential element analysis table, summarize by promoter, include Ensembl ids

In [ ]:
#data file spec sheet